version: "3.8"
services: 
  database: 
    image: daryl7817/mysql:latest
    build: ./database
    container_name: mysql
    ports: 
    - target: 3306
      published: 3306
    environment: 
      MYSQL_ROUTE_PASSWORD: password
  backend: 
    container_name: backend
    image: daryl7817/backend:latest
    build: ./backend
    ports:
    - target: 5001
      published: 5001
  frontend:
    container_name: frontend
    image: daryl7817/frontend:latest
    build: ./frontend
    ports:
    - target: 5000
      published: 5000
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
    - target: 80
      published: 80
    volumes: 
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
